// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTnSbV_8tGfpBlpIgi2-u8HJqU0IXsboQ',
    appId: '1:676909764704:web:38d4a2a029a5c0c7277305',
    messagingSenderId: '676909764704',
    projectId: 'lucasadriano-firebase-app',
    authDomain: 'lucasadriano-firebase-app.firebaseapp.com',
    storageBucket: 'lucasadriano-firebase-app.firebasestorage.app',
    measurementId: 'G-RN24Z1PXXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgthCTd2Jd8y8EwRWMfrXUxbbCHw6hJs',
    appId: '1:676909764704:android:68528353e0a16684277305',
    messagingSenderId: '676909764704',
    projectId: 'lucasadriano-firebase-app',
    storageBucket: 'lucasadriano-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtkPN-ZeV1A2JFrFJGgtG-akNlQxhM6E8',
    appId: '1:676909764704:ios:83bc72113ff94447277305',
    messagingSenderId: '676909764704',
    projectId: 'lucasadriano-firebase-app',
    storageBucket: 'lucasadriano-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.modulo8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtkPN-ZeV1A2JFrFJGgtG-akNlQxhM6E8',
    appId: '1:676909764704:ios:83bc72113ff94447277305',
    messagingSenderId: '676909764704',
    projectId: 'lucasadriano-firebase-app',
    storageBucket: 'lucasadriano-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.modulo8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTnSbV_8tGfpBlpIgi2-u8HJqU0IXsboQ',
    appId: '1:676909764704:web:1f0daf847e33105d277305',
    messagingSenderId: '676909764704',
    projectId: 'lucasadriano-firebase-app',
    authDomain: 'lucasadriano-firebase-app.firebaseapp.com',
    storageBucket: 'lucasadriano-firebase-app.firebasestorage.app',
    measurementId: 'G-V4SNB19H4H',
  );

}